backend:
  name: github
  repo: x26prakhar/website
  branch: main
  base_url: https://prakhar-website-astro.vercel.app
  auth_endpoint: api/auth

media_folder: public/images
public_folder: /images

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Category", name: "category", widget: "select", options: ["VC and Startups", "AI", "Economics and Public Policy", "Personal", "Others"], multiple: true }
      - { label: "Body", name: "body", widget: "markdown", required: false }
